name: macOS 10.15

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt6
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.1'
      - name: Install depedencies using brew
        run: brew install nlohmann-json cpprestsdk openssl eigen cereal
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build with CMake
        run: cmake --build build --config Release
      - name: Bundle with CPack
        run: cpack
      - name: Publish bundle
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.dmg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
