name: macOS 10.15

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install codesign certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CODESIGN_CERTIFICATE }}
          p12-password: ${{ secrets.CODESIGN_CERTIFICATE_PASSWORD }}
      - name: Install depedencies using brew
        run: |
          brew install nlohmann-json cpprestsdk openssl eigen cereal qt@6
      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SERVICE=OFF -DCODESIGN_CERTIFICATE_NAME="Developer ID Application: Tobias Hegemann (JH3275598G)"
      - name: Build with CMake
        run: cmake --build build --config Release
      - name: Bundle with CPack
        run: cpack --config build/CPackConfig.cmake -B build -G DragNDrop
      - name: Publish bundle
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.dmg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true