name: Nighly for Windows

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

env:
  BUILD_TYPE: Release
  WXVERSION: 3.1.4

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Conan package manager
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Install depedencies using Conan package manager
        run: |
          conan install -if build --build missing .
      - name: Configure CMake
        run: |
          cmake -S . -B build -DUSE_GNUTLS=0 -DCMAKE_BUILD_TYPE=Release -DBUILD_SERVICE=OFF -DwxWidgets_USE_DEBUG=false -DwxWidgets_USE_UNICODE=true -DwxWidgets_USE_STATIC=true
      - name: Build with CMake
        run: cmake --build build --config Release
      - name: Bundle App
        run: cpack --config build/CPackConfigApp.cmake -B build
      - name: Publish installer
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.exe,build/*.zip"
          bodyFile: "HOWTO.md"
          commit: "main"
          tag: "Nightly"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
