name: Nighly for macOS 10.15

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

env:
  BUILD_TYPE: Release
  WXVERSION: 3.1.4
  cache-name: cache-wxWidgets

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get version
        run: |
          FULL_VERSION=$(git describe --tags --abbrev=0)
          echo '::set-output name=VERSION::$(echo ${FULL_VERSION:1})'
        id: get-version
      - name: Install codesign certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CODESIGN_CERTIFICATE }}
          p12-password: ${{ secrets.CODESIGN_CERTIFICATE_PASSWORD }}
      - name: Install wxwidget
        run: brew install wxwidgets
      - name: Install depedencies using conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
          conan install -if build --build missing .
      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DMACOSX_DEPLOYMENT_TARGET=10.14 -DCODESIGN_CERTIFICATE_NAME="Developer ID Application: Tobias Hegemann (JH3275598G)"
      - name: Build with CMake
        run: cmake --build build --config Release
      - name: Bundle App
        run: cpack --config build/CPackConfigApp.cmake -B build
      - name: Bundle Service
        run: cpack --config build/CPackConfigService.cmake -B build

      - name: Rename to nighly
        run: |
          mv build/digital-stage-connector-${{ steps.get-version.outputs.VERSION }}-Darwin-app.dmg build/digital-stage-connector-nightly-Darwin-app.dmg
          mv build/digital-stage-connector-${{ steps.get-version.outputs.VERSION }}-Darwin-service.dmg build/digital-stage-connector-nightly-Darwin-service.dmg
      - name: Sign bundle
        run: |
          codesign --force --options runtime --sign "Developer ID Application: Tobias Hegemann (JH3275598G)" build/digital-stage-connector-nightly-Darwin-app.dmg
      - name: Notarize App bundle
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: "build/digital-stage-connector-nightly-Darwin-app.dmg"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
          primary-bundle-id: de.tobiashegemann.digital-stage.app
      - name: Staple App bundle
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: "build/digital-stage-connector-nightly-Darwin-app.dmg"

      - name: Publish bundle
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.dmg,build/*.zip"
          bodyFile: "HOWTO.md"
          commit: "main"
          tag: "Nightly"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}