name: Windows

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt6
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.1'
      - name: Install openssl
        run: choco install openssl
      - name: Install Conan package manager
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Install depedencies using Conan package manager
        run: conan install -if build --build missing .
      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_SERVICE=OFF -DUSE_GNUTLS=0 -DCMAKE_BUILD_TYPE=Release
      - name: Build with CMake
        run: cmake --build build --config Release
      - name: Bundle with CPack
        run: cpack --config build/CPackConfig.cmake -B build
      - name: Publish installer
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          bodyFile: "HOWTO.md"
          token: ${{ secrets.GITHUB_TOKEN }}