name: Windows

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-toolchain
          msystem: mingw64
          release: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.1'
          host: "windows"
          target: "desktop"
          arch: "win64_mingw73"
          dir: "${{github.workspace}}/qt/"
          install-deps: "true"

      - name: Install Conan package manager
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Install depedencies using Conan package manager
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.cppstd=17 default
          conan profile update settings.compiler.runtime=static default
          conan install -if build --build missing .
      - name: Configure CMake
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        run: cmake -S . -B build -G "CodeBlocks - MinGW Makefiles" -DBUILD_SERVICE=OFF -DUSE_GNUTLS=0 -DCMAKE_BUILD_TYPE=Release
      - name: Build with CMake
        run: cmake --build build --config Release
      - name: Bundle with CPack
        run: cpack --config build/CPackConfig.cmake -B build
      - name: Publish installer
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          bodyFile: "HOWTO.md"
          commit: "main"
          tag: "Nightly"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}